modLoader="javafml"
loaderVersion="[36,)"
license=""
logoFile="Figure_1.png"

[[mods]]
modId="cruelfishing"
displayName="Cruel Fishing"
authors="igorstan"

description='''
Enter the world of fish and become who you were meant to be.
'''

[[dependencies.cruelfishing]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cruelfishing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
